#!/usr/bin/php -q
<?php
error_log( "输入的 ip 为:" . $ip_dec = $argv[1]);
// error_log( "网段位数为:".$segment = $argv[2]);
error_log( "需要划分的子网个数为:" . $sub_segment_count = $argv[2]);
error_log( "每个子网的主机不小于:".$limit_count = $argv[3]);


function bin2ip($bin){
	$net_arr = str_split($bin,8);
	$net_arr_dec;
	foreach($net_arr as $v){
		$net_arr_dec[] = bindec($v);
	}
	return join($net_arr_dec,'.');
}

function ip2bin($ip){
	foreach(explode('.',$ip) as $v){
		$ip_arr[] = str_pad(decbin($v),8,'0',STR_PAD_LEFT);
	}
	return join($ip_arr);
}

function bin_inverse($ip){
	$len = strlen($ip);
	$ret = '';
	for($i = 0; $i < $len ;$i++){
		if($ip[$i] == 0){
			$ret .= '1';
		}else{
			$ret .= '0';
		}
	}
	return $ret;
}


// 该 ip 对应的网段
/*
$net  = join(array_pad([],$segment,1)).join(array_pad([],32 - $segment,0));
error_log("该ip子网掩码为:".bin2ip($net));
$ip_bin = ip2bin($ip_dec);


$net_addr = '';
error_log("子网掩码: ".$net);
error_log("用户挨批: ".$ip_bin);
for($i = 0;$i < 32; $i++){
	$net_addr .= $net[$i] & $ip_bin[$i];
}
error_log("网络地址: ".$net_addr);
error_log("网络地址: ".bin2ip($net_addr));

$net_rev = bin_inverse($net);
$blog_addr = '';
for($i = 0;$i < 32; $i++){
	$blog_addr .= $net_rev[$i] | $ip_bin[$i];
}
error_log("广播地址: ".$blog_addr);
error_log("广播地址: ".bin2ip($blog_addr));
*/













